Repository b-side-g1/Dive, pull requests merged in 2020-10, with the labels that each got.

#197 추이 그래프 & 테스트 #196
  lib/commons/function.dart
  lib/services/daily/daily_service.dart
  lib/services/statistics/statistics_service.dart
  lib/vo/statistics_vo.dart
  test/services/statistics/statistics_service_test.dart
Labels: 리뷰요청, 서브 브랜치

#200 Feature/statistics card #198
  lib/services/statistics/statistics_service.dart
  test/services/statistics/statistics_service_test.dart
Labels: 리뷰요청, 서브 브랜치

#203 상세 페이지 서비스 추가 #202
  lib/services/statistics/statistics_service.dart
  test/services/statistics/statistics_service_test.dart
Labels: 리뷰요청, 서브 브랜치

#201 먼슬리 리포트(BE - statistics service)
  lib/services/statistics/statistics_service.dart
  test/services/statistics/statistics_service_test.dart
Labels: 메인 브랜치, 진행중

#208 [리스트페이지] 점수 삭제 버튼 미노출 #207
  lib/components/forms/recording_form.dart
  lib/components/time_picker.dart
  lib/pages/daily_page.dart
  lib/src/image/daily/icon_trash_ori.png
Labels: 리뷰요청

#209 이유 별 평점, 감정 별 평점 추가, 그래프 데이터 일별 추가
  lib/services/statistics/statistics_service.dart
  test/services/statistics/statistics_service_test.dart
Labels: 리뷰요청
