Repository b-side-g1/Dive, pull requests merged in 2020-08, with the labels that each got.

#70 #69 add third party library for toast 태그 5개 이상 선택 시 토스트 메시지 출력
  lib/components/emotion_tag_box.dart
  lib/components/input/step3/reason_tag_widget.dart
  lib/services/common/common_service.dart
  pubspec.lock
  pubspec.yaml
Labels: 리뷰요청, 메인 브랜치, 진행중

#72 #71 스탭3 에서 스탭 1, 2 데이터 가져오기
  lib/components/emotion_tag_box.dart
  lib/components/input/step3/reason_tag_widget.dart
  lib/components/input/step3/save_tag_button.dart
  lib/inherited/state_container.dart
  lib/pages/daily_page.dart
  lib/pages/input_page.dart
  lib/pages/input_page_step1.dart
  lib/pages/input_page_step2.dart
  lib/pages/input_page_step3.dart
Labels: 리뷰요청, 메인 브랜치, 진행중

#89 입력 리스트 삭제 기능 구현
  lib/pages/daily_page.dart
Labels: 리뷰요청

#87 기록하기 버튼이 이미지에 가려지는 점 수정
  lib/pages/input_page.dart
  lib/pages/input_page_step1.dart
  lib/pages/input_page_step2.dart
  lib/pages/input_page_step3.dart
Labels: 리뷰요청, 메인 브랜치, 진행중

#91 인풋페이지 스탭3 프로바이더 제거
  lib/components/input/step3/edit_tag_dialog.dart
  lib/components/input/step3/edit_tag_list.dart
  lib/components/input/step3/reason_tag_widget.dart
  lib/pages/input_page.dart
  lib/pages/input_page_step1.dart
  lib/pages/input_page_step3.dart
Labels: 리뷰요청, 진행중

#140 [QA-ISSUE] 입력 후 리스트에 안나오는 버그
  lib/services/daily/daily_service.dart
  lib/services/record/record_service.dart
Labels: 리뷰요청

#153 [QA-ISSUE] 이유태그 노출 순서 변경
  lib/components/input/step3/edit_tag_list.dart
  lib/services/database/database_helper.dart
  lib/services/tag/tag_service.dart
Labels: 리뷰요청
